version: '3'
services:
  database:
    container_name: database
    image: postgres:14
    env_file: 
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  redis:
    container_name: redis
    image: redis:7.0
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 32773:6379
    sysctls:
      - net.core.somaxconn=324000
      - net.ipv4.tcp_max_syn_backlog=3240000
    restart: always
  newleaf:
    image: abeltramo/newleaf:latest
    container_name: newleaf
    restart: always
    ports:
      - 3241:3000
    volumes:
      - ./newleaf/configuration.py:/workdir/configuration.py
  rsync:
    image: mchangrh/rsync:latest
    container_name: rsync
    restart: always
    ports:
      - 873:873
    volumes:
      - ./rsync/rsyncd.conf:/etc/rsyncd.conf
      - ./database-export/:/mirror

volumes:
  database-data:
