BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "votes" (
	"UUID"	TEXT NOT NULL,
	"userID"	INTEGER NOT NULL,
	"hashedIP"	INTEGER NOT NULL,
	"type"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "sponsorTimes" (
	"videoID"	TEXT NOT NULL,
	"hashedIP"	TEXT NOT NULL,
	"timeSubmitted"	INTEGER NOT NULL
);
COMMIT;
