name: PostgreSQL CI

on: [push, pull_request]

jobs:
  build:
    name: Run Tests with PostgreSQL
    runs-on: ubuntu-latest

    steps:
      - uses: ajayyy/SponsorBlockServer/.github/workflows/node-setup.yml@master
      - name: Build the docker-compose stack
        env:
          PG_USER: ci_db_user
          PG_PASS: ci_db_pass
        run: docker-compose -f docker/docker-compose-ci.yml up -d
      - name: Check running containers
        run: docker ps
      - name: Run Tests
        env:
          TEST_POSTGRES: true
        timeout-minutes: 5
        run: npm test