name: SQLite CI

on: [push, pull_request]

jobs:
  build:
    name: Run Tests with SQLite
    runs-on: ubuntu-latest

    steps:
      - uses: ajayyy/SponsorBlockServer/.github/workflows/node-setup.yml@master
      - name: Run Tests
        timeout-minutes: 5
        run: npm test
