name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Lint with ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: ajayyy/SponsorBlockServer/.github/workflows/node-setup.yml@master
      - name: Run Tests
        timeout-minutes: 5
        run: npm run lint